name: Build and Release

on:
  push:
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create plugin zip
        run: |
          mkdir -p dist/equalstrue
          rsync -a ./ dist/equalstrue/ \
            --exclude-from=".distignore" \
            --exclude ".github/" \
            --exclude "dist/"

          cd dist
          zip -r equalstrue-${{ github.ref_name }}.zip equalstrue

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/equalstrue-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
